language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script: 
  - asdf plugin-add kubectl ./
  - asdf list-all kubectl
  - asdf plugin-test kubectl ./ --asdf-plugin-gitref $TRAVIS_COMMIT 'kubectl version --client=true'
os:
  - linux
  - osx
arch:
  - amd64
  - arm64
  - ppc64le
